export * as professor from "./undraw_professor_re_mj1s.svg"
export * as streamline from "./undraw_heavy_box_agqi.svg"
export * as schedule from "./undraw_events_re_98ue.svg"
export * as digitalLibrary from "./undraw_online_reading_np7n.svg"
export * as customize from "./undraw_switches_1js3.svg"
